name: ocetrac-unstruct
channels:
  - conda-forge
dependencies:
  # Required for full project functionality 
  - pytest
  # Examples 
  - jupyter
  - jupyterlab
  - xarray
  - numpy
  - numba
  - jax
  - jaxlib
  - scipy
  - dask
  - scikit-image
  - dask_image
